# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Material Jekyll Theme
email: niels.mentink@outlook.com
copyright: © 2017 Niels Mentink
description: >- # this means to ignore newlines until "baseurl:"
  A jekyll theme inspired by google's design filosophy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# trackingid: # the google analytics tracking id for your site

navigation:
  - title: Home
    url: /#
  - title: Blog
    url: /blog/
  - title: About
    url: /about/

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: niels.mentink@outlook.com
  facebook:
  github:
  instagram: nmentink
  linkedin:
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCSqrzfiWbzETJALMJcu8d2w # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Disables date in url
permalink: /blog/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: :compressed
